development: &local
  app_url: "http://localhost:3000"
  public_key_passphrase: "projectvision"
  redis_list_name: "imap_messages"

test:
  <<: *local

production:
  app_url: "http://projectvision.heroku.com/"
  public_key_passphrase: "projectvision"


