development: &local
  app_url: "http://localhost:3000"
  public_key_passphrase: "projectvision"
  redis_list_name: "imap_messages"
  processor:
    imap_poll_interval: 3600
    redis_poll_interval: 20

test:
  <<: *local

production:
  app_url: "http://projectvision.heroku.com/"
  public_key_passphrase: "projectvision"
  polling_interval: 3600
  redis_list_name: "imap_messages"
  processor:
    imap_poll_interval: 3600
    redis_poll_interval: 20
